CREATE TABLE IF NOT EXISTS organizations (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_organization VARCHAR(255) NOT NULL,
    little_name_position VARCHAR(50) NOT NULL,
    name_director VARCHAR(50) NOT NULL,
    surname_director VARCHAR(50) NOT NULL,
    inn BIGINT NOT NULL,
    okved BIGINT NOT NULL,
    adress VARCHAR(250) NOT NULL,
    phone_organization VARCHAR(50) NOT NULL,
    email_organization VARCHAR(50) NOT NULL,
    CONSTRAINT pk_organization PRIMARY KEY (organization_id)
);

CREATE TABLE IF NOT EXISTS departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_department VARCHAR(200) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    CONSTRAINT pk_department PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS positions (
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_position VARCHAR(100) NOT NULL,
    description_position VARCHAR(500) NOT NULL,
    department_id BIGINT NOT NULL REFERENCES departments(department_id),
    CONSTRAINT pk_position PRIMARY KEY (position_id)
);

CREATE TABLE IF NOT EXISTS myuser (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(100) NOT NULL,
    surname VARCHAR(500) NOT NULL,
    email VARCHAR(100) NOT NULL,
    login VARCHAR(500) NOT NULL,
    password VARCHAR(500) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    position_id BIGINT NOT NULL REFERENCES positions(position_id),
    active BOOL NOT NULL,
    CONSTRAINT pk_myuser PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL REFERENCES myuser(user_id),
    role VARCHAR(500) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id)
);

